name: Build and Deploy Astro

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout source
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Install Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      # Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Build Astro
      - name: Build Site
        run: npm run build

      # Deploy dist to deploy branch
      - name: Deploy to deploy branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: deploy
